/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.bookboxd.view;

import br.com.ifba.bookboxd.controller.AutorController;
import br.com.ifba.bookboxd.controller.EditoraController;
import br.com.ifba.bookboxd.controller.LivroController;
import br.com.ifba.bookboxd.controller.UsuarioController;
import br.com.ifba.bookboxd.entity.Usuario;
import br.com.ifba.bookboxd.infrastruture.util.SpringContextHolder;

public class DashboardView extends javax.swing.JFrame {
    
    private final Usuario usuarioLogado;
    private final UsuarioController usuarioController;
    private final LivroController   livroController;
    private final AutorController   autorController;
    private final EditoraController editoraController;
    
    public DashboardView(Usuario usuarioLogado, UsuarioController usuarioController) {
        this.usuarioLogado = usuarioLogado;
        this.usuarioController = usuarioController;
        this.livroController = SpringContextHolder.getBean(LivroController.class);
        this.autorController   = SpringContextHolder.getBean(AutorController.class);
        this.editoraController = SpringContextHolder.getBean(EditoraController.class);
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
